server:
  port: 6060
  enable-http-2: true
  database:
    hikari: true
    host: 192.168.1.196
    port: 5432
    username: postgres
    password: yfM478rEK207BBA355stk059joK399CX
    driver_class_name: org.postgresql.Driver
    name: todo_app
    max_pool_size: 10
    initial_pool_size: 5
    max_timeout: 10
    type: POSTGRESQL
database:
  generate_sql: true
  source_type: postgresql
