server:
  port: 6060
  enable-http-2: true
  enable-metrics: true
  database:
    host: ${DATABASE_HOST:192.168.1.196}
    port: ${DATABASE_PORT:5432}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:yfM478rEK207BBA355stk059joK399CX}
    driver_class_name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    name: ${DATABASE_NAME:todo_app}
    max_pool_size: ${DATABASE_MAX_POOL_SIZE:10}
    initial_pool_size: ${DATABASE_INITIAL_POOL_SIZE:5}
    max_timeout: ${DATABASE_MAX_TIMEOUT:10}
    type: ${DATABASE_TYPE:POSTGRESQL}
    use_cache: true
database:
  generate_sql: false
  source_type: postgresql
