server:
  port: 6060
  enable-http-2: true
  enable-metrics: true
  reactive:
    database:
      host: ${REACTIVE_DATABASE_HOST:localhost}
      port: ${REACTIVE_DATABASE_PORT:1521}
      username: ${REACTIVE_DATABASE_USERNAME:SYS}
      password: ${REACTIVE_DATABASE_PASSWORD:ayn802Wm}
      name: ${REACTIVE_DATABASE_NAME:FREE}
      max_pool_size: ${REACTIVE_DATABASE_MAX_POOL_SIZE:10}
      type: ${REACTIVE_DATABASE_TYPE:ORACLE}
database:
  generate_sql: false
  source_type: postgresql
